# Generated by Django 5.2.7 on 2025-10-16 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='is_school_admin',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='school',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher', to='accounts.school'),
        ),
    ]
