# Generated by Django 5.2.7 on 2025-10-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_teacherprofile_is_school_admin_and_more'),
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='completed_levels',
            field=models.ManyToManyField(blank=True, to='learning.level'),
        ),
    ]
